### ISSUE TITLE
Blog not accesible anymore. (http://philipperemy.github.io/keras-stateful-lstm/)

### ISSUE THREAD

**Issue by 108anup** [philipperemy/philipperemy.github.io#2]
Hi, I think your blog is not accessible anymore. (e.g. this link does not work anymore: http://philipperemy.github.io/keras-stateful-lstm/)

**Comment by philipperemy** [comment]
@108anup yes will re-deploy it ;)

**Comment by philipperemy** [comment]
@108anup done!
