### ISSUE TITLE
The Falun Gong cult account you follow

### ISSUE THREAD

**Issue by ThomasMrY** [philipperemy/philipperemy.github.io#3]
hi,
Sorry to comment here. The Falun Gong cult account you follow (cirosantilli.com) uses lies to stigmatize the Chinese government, the Communist Party of China, and Xinjiang. Any Chinese would not want to see you believe this. If you really do Interested in China, please visit China to learn the truth.
Thanks,
Thomas

**Comment by philipperemy** [comment]
@ThomasMrY right good point I didn't really read. I just found the layout funny. I'm going to unfollow.
